#!/usr/bin/env bash

cp .env.dev.sample .env.dev

docker-compose build

docker-compose run --rm rails rails new . --force --database=postgresql --skip-bundle --skip-git --skip-test
sudo chown -R $USER .

sed -i -e "s/# gem 'therubyracer'/gem 'therubyracer'/" Gemfile

docker-compose run --rm rails bundle update
sudo chown -R $USER .

cp -f template/database.yml config/database.yml

docker-compose run --rm rails bundle exec spring binstub --all
sudo chown -R $USER .
